package com.example.enums;

public enum DocumentType {
    COMPANY_PAN_CARD,
    CERTIFICATE_OF_INCORPORATION,
    MOA,
    AOA,
    BOARD_RESOLUTION,
    COMPANY_ADDRESS_PROOF,
    COMPANY_BANK_ACCOUNT_PROOF,
    BALANCE_SHEET,
    CA_NET_WORTH_CERTIFICATE,
    DIRECTOR_PAN_CARD,
    DIRECTOR_AADHAAR_CARD,
    USER_AADHAAR_CARD,
    USER_PAN_CARD
}
